### ISSUE TITLE
Steps for installation?

### ISSUE THREAD

**Issue by MaryCoding** [vdaubry/youtube-multiple-dl#1]
Hi Vdaubry, I am running youtuble-dl from linux machine. I was able to clone using git. However, I am a little confused with the rest of the installation. Could you provide some insight? I am running this on Ubuntu Vivid. Thanks.

**Comment by vdaubry** [comment]
Hi marry, did you manage to run the `bundle install` command ?

**Comment by MaryCoding** [comment]
Hi @vdaubry yes I was able to run `bundle install`. However it stalls when i start `youtube-multiple-dl` and nothing downloads. How did you set the path environments for this? I am running this on my Ubuntu 15.04 box

**Comment by vdaubry** [comment]
In order to start a download make sure that you add some URL to download :

`youtube-multiple-dl -add https://www.youtube.com/watch?v=Y7RnH6bnGHc`

You can check that you have some URL in your queue with the `list` option :

`youtube-multiple-dl --list`

When you have some URL in your queue you can start some workers, 3 workers will download 3 video simultaneously :

`youtube-multiple-dl --start --worker_number 3`

Once you have started the workers you can open another tab and add some more urls, they will be added to the queue and automaticcaly downloaded when other downloads have finished.

**Comment by MaryCoding** [comment]
Thanks!
